tag_locations:
frame_id: "map"   # Global reference frame for all tags

tags:

```
# -----------------------------
# TAG 0
# -----------------------------
- id: 0
  pose:
    position:
      x: 2.0     # meters
      y: 1.0
      z: 0.0
    orientation:   # Quaternion (preferred)
      x: 0.0
      y: 0.0
      z: 0.7071
      w: 0.7071

# -----------------------------
# TAG 1
# -----------------------------
- id: 1
  pose:
    position:
      x: 5.0
      y: 0.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

# -----------------------------
# TAG 2
# -----------------------------
- id: 2
  pose:
    position:
      x: 4.5
      y: 3.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.7071
      w: 0.7071

# -----------------------------
# TAG 3
# -----------------------------
- id: 3
  pose:
    position:
      x: 1.0
      y: 4.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0
```
